image: node:latest

stages:
  - build
  - deploy

build_app:
  image: node:alpine
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build
    - tar -zcvf myapp.tar.gz ./dist ./appspec.yml
    - mkdir -p deploy
    - mv myapp.tar.gz deploy/myapp.tar.gz
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
      - deploy/
    expire_in: 1 hour

variables:
  S3_BUCKET_NAME: "vue-websocket-service"

deploy:

  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - ls -al
    - pwd
    - aws s3 cp deploy s3://$S3_BUCKET_NAME/ --recursive --include "*"
  only:
    - master

  when: manual
